In [ ]:
# Run Date: Monday, June 05, 2023
# Run Time: 00:05:59

In [1]:
import time
from datetime import date

startTime = time.time()
todaysDate = date.today()

# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

2023-06-05 14:25:49.187720: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-05 14:25:49.301291: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


## 0. Parameters <a name="parameters"></a>

In [3]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [4]:
wineMagData = '/tf/All/Data/Documents/Github/davidADSP/data/WineReviews/winemag-data-130k-v2.json'

In [5]:
# Load the full dataset
with open(wineMagData) as json_data:
    wine_data = json.load(json_data)

In [6]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [7]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [8]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [9]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [10]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [11]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [12]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

2023-06-05 14:25:57.937286: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-05 14:25:57.937476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-05 14:25:57.939463: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-05 14:25:57.939613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-05 14:25:57.939750: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from S

In [13]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [14]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [15]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [16]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [17]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [18]:
example_input_output = train_ds.take(1).get_single_element()

In [19]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,  264,    2, 1494,    2,  496,  533,    2,    8,
        783,   60,  794, 1282,    8,   56,  186,   14,  292,   28,   25,
         13, 2514,   47,  263, 1897,    5,   38,  222,  523,  115,   22,
         25,   13,  131, 2353,   47,   81,  195,    4,   12,   13,  157,
        186,   19,   35,    5,  157,  247,   11,   25, 1897,    4,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [20]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,  264,    2, 1494,    2,  496,  533,    2,    8,  783,
         60,  794, 1282,    8,   56,  186,   14,  292,   28,   25,   13,
       2514,   47,  263, 1897,    5,   38,  222,  523,  115,   22,   25,
         13,  131, 2353,   47,   81,  195,    4,   12,   13,  157,  186,
         19,   35,    5,  157,  247,   11,   25, 1897,    4,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [21]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [22]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [23]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [24]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [25]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddin  (None, None, 256)        2580480   
 g (TokenAndPositionEmbeddin                                     
 g)                                                              
                                                                 
 transformer_block (Transfor  ((None, None, 256),      658688    
 merBlock)                    (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5,809,168
Trainable params: 5,809,168
Non-trainable params: 0
___________________________________________________

In [26]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("09_01_gpt/models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [27]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [28]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="09_01_gpt/checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="09_01_gpt/logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [29]:
%%time
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 [==============================] - ETA: 0s - loss: 2.2574 - dense_2_loss: 2.2574
generated text:
wine review : italy : sicily & sardinia : grillo : based [UNK] [UNK] [UNK] blends in portugal ( campania ) boasts aromas of green apple , incense and banana . the wine is simple and simple but genuine overall finesse , there ' s a clean , fresh quality and freshness . 

4060/4060 [==============================] - 68s 16ms/step - loss: 2.2574 - dense_2_loss: 2.2574
Epoch 2/5
4058/4060 [============================>.] - ETA: 0s - loss: 1.9597 - dense_2_loss: 1.9597
generated text:
wine review : south africa : stellenbosch : cabernet sauvignon : this playful blend of spicy spice and red - fruit forward fruit , prickly and cocoa spice aromas on the nose . the palate leads in a freshly tannic style that doesn ' t take heavy or textural . 

4060/4060 [==============================] - 67s 16ms/step - loss: 1.9596 - dense_2_loss: 1.9596
Epoch 3/5
4059/4060 [===================

In [30]:
# Save the final model
gpt.save("09_01_gpt/models/gpt")

INFO:tensorflow:Assets written to: 09_01_gpt/models/gpt/assets


INFO:tensorflow:Assets written to: 09_01_gpt/models/gpt/assets


# 3. Generate text using the Transformer

In [31]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [32]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : california : zinfandel : this blend of syrah , petite sirah , is flavorful , tannic and ideal for drinking now . the raspberry pie , beef jerky and dark bacon fat flavors coat the palate , a bit of overripeness , and seems to mute the function of its cool origins . 



In [33]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : piedmont : nebbiolo : this opens with aromas suggesting toast , espresso , stewed black - skinned fruit and a balsamic note . the palate offers dried black cherry , clove and a hint of star anise alongside assertive , close - grained tannins . drink through 2021 . 



In [34]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : while the nose is a bit demure , with hints of struck flint and slate . the palate is more mineral and zesty , it also has a steely , minerally feel and a long finish . drink now through 2020 . 



::   	100.0%
-:   	0.0%
grosso:   	0.0%
africa:   	0.0%
zealand:   	0.0%
--------



mosel:   	96.92%
rheingau:   	2.08%
pfalz:   	0.47%
rheinhessen:   	0.31%
württemberg:   	0.08%
--------



::   	99.25%
-:   	0.75%
grosso:   	0.0%
,:   	0.0%
blanca:   	0.0%
--------



riesling:   	99.99%
pinot:   	0.0%
sparkling:   	0.0%
white:   	0.0%
rosé:   	0.0%
--------



::   	100.0%
-:   	0.0%
grosso:   	0.0%
blanc:   	0.0%
blanca:   	0.0%
--------



a:   	19.44%
while:   	19.42%
dusty:   	15.13%
this:   	9.01%
fresh:   	7.58%
--------



the:   	60.57%
intensely:   	12.13%
this:   	6.81%
dry:   	2.94%
demure:   	2.41%
--------



nose:   	96.57%
palate:   	2.65%
attack:   	0.25%
[UNK]:   	0.12%
mouthfeel:   	0.1%
--------



is:   	78.58%
on:   	17.99%
of:   	2.02%
offers:   	0.34%
suggests:   	0.3%
--------



demure:   	78.12%
a:   	13.12%
quite:   	1.11%
subdued:   	0.75%
fresh:   	0.65%
--------



bit:   	84.81%
touch:   	8.78%
hint:   	2.09%
little:   	0.82%
whiff:   	0.57%
--------



demure:   	93.83%
subdued:   	2.77%
closed:   	0.81%
lean:   	0.44%
more:   	0.34%
--------



,:   	91.88%
on:   	6.59%
in:   	0.91%
and:   	0.47%
.:   	0.12%
--------



with:   	36.89%
this:   	33.77%
but:   	9.46%
suggesting:   	5.66%
the:   	5.36%
--------



a:   	61.91%
hints:   	5.75%
delicate:   	5.57%
sweet:   	3.87%
notes:   	3.04%
--------



of:   	100.0%
suggesting:   	0.0%
at:   	0.0%
to:   	0.0%
that:   	0.0%
--------



struck:   	79.48%
petrol:   	7.57%
slate:   	2.34%
smoke:   	1.58%
mineral:   	0.76%
--------



flint:   	99.98%
-:   	0.01%
match:   	0.0%
steel:   	0.0%
apple:   	0.0%
--------



and:   	93.54%
,:   	6.45%
on:   	0.0%
or:   	0.0%
.:   	0.0%
--------



slate:   	94.9%
struck:   	0.95%
flint:   	0.95%
smoke:   	0.62%
crushed:   	0.58%
--------



.:   	79.23%
,:   	8.92%
accenting:   	6.56%
on:   	3.19%
that:   	1.16%
--------



the:   	86.49%
it:   	12.31%
this:   	0.5%
there:   	0.28%
on:   	0.21%
--------



palate:   	99.84%
mouthfeel:   	0.11%
mouth:   	0.03%
flavors:   	0.01%
finish:   	0.0%
--------



is:   	98.75%
offers:   	0.35%
shows:   	0.17%
has:   	0.14%
on:   	0.12%
--------



a:   	19.87%
rich:   	8.73%
plush:   	5.96%
bright:   	5.64%
full:   	5.37%
--------



delicate:   	19.28%
subdued:   	9.36%
steely:   	9.07%
pronounced:   	7.56%
concentrated:   	6.41%
--------



and:   	45.77%
,:   	25.1%
than:   	16.53%
-:   	10.86%
tones:   	0.83%
--------



steely:   	15.52%
savory:   	12.86%
mineral:   	12.62%
slate:   	6.99%
smoke:   	4.79%
--------



,:   	97.36%
on:   	1.01%
than:   	0.66%
lime:   	0.28%
in:   	0.27%
--------



with:   	46.96%
it:   	37.35%
this:   	6.69%
the:   	3.8%
but:   	2.88%
--------



':   	88.93%
offers:   	6.07%
shows:   	1.36%
finishes:   	1.23%
is:   	0.53%
--------



shows:   	46.81%
has:   	23.96%
offers:   	22.43%
boasts:   	2.54%
packs:   	1.12%
--------



a:   	97.66%
an:   	1.36%
the:   	0.2%
tart:   	0.1%
more:   	0.09%
--------



delicate:   	13.08%
crisp:   	11.18%
tart:   	8.99%
zesty:   	6.11%
brisk:   	4.65%
--------



,:   	67.14%
spine:   	9.41%
edge:   	6.09%
backbone:   	4.7%
minerality:   	2.78%
--------



mineral:   	44.65%
minerally:   	43.46%
stony:   	3.76%
steely:   	2.61%
taut:   	2.01%
--------



feel:   	73.32%
profile:   	5.12%
backbone:   	4.78%
character:   	3.25%
texture:   	2.93%
--------



and:   	48.85%
.:   	28.02%
,:   	10.12%
that:   	8.89%
to:   	3.73%
--------



a:   	95.94%
the:   	0.79%
crisp:   	0.42%
an:   	0.32%
just:   	0.22%
--------



bit:   	62.9%
touch:   	18.98%
long:   	7.51%
lingering:   	3.32%
stony:   	1.52%
--------



,:   	72.87%
finish:   	21.94%
-:   	5.16%
and:   	0.01%
but:   	0.0%
--------



.:   	93.63%
that:   	5.85%
,:   	0.26%
of:   	0.18%
with:   	0.06%
--------



:   	80.77%
drink:   	16.03%
it:   	2.33%
the:   	0.46%
a:   	0.11%
--------



now:   	98.48%
it:   	0.47%
this:   	0.37%
after:   	0.24%
through:   	0.14%
--------



through:   	96.88%
.:   	2.84%
but:   	0.19%
or:   	0.04%
to:   	0.02%
--------



2020:   	55.15%
2021:   	10.31%
2019:   	6.42%
2010:   	5.92%
2018:   	5.25%
--------



.:   	99.97%
to:   	0.02%
or:   	0.0%
,:   	0.0%
through:   	0.0%
--------



:   	100.0%
imported:   	0.0%
the:   	0.0%
it:   	0.0%
try:   	0.0%
--------



In [35]:
endTime = time.time()

elapsedTime = time.strftime("%H:%M:%S", time.gmtime(endTime - startTime))

print(todaysDate.strftime('# Run Date: %A, %B %d, %Y'))
print(f"# Run Time: {elapsedTime}")

# Run Date: Monday, June 05, 2023
# Run Time: 00:05:59
